import os
import urllib.request
import subprocess
import traceback

# STATIC_CATEGORIES 字典
STATIC_TV_NAMES = {
    "MBC 2": "MBC 2",
    "MBC Max": "MBC Max",
    "MBC Action": "MBC Action",
    "MBC Movies": "MBC Movies",
    "MBC Movies Action": "MBC Movies Action",
    "MBC Movies Thriller": "MBC Movies Thriller",
    "Canal+ Cinema": "Canal+ Cinema",
    "Canal+ Box Office": "Canal+ Box Office",
    "Canal+ Grand Ecran": "Canal+ Grand Ecran",
    "Canal+ France": "Canal+ France",
    "SkyCinema Premiere": "SkyCinema Premiere",
    "SkyCinema Action": "SkyCinema Action",
    "SkyStore Premier 1": "SkyStore Premier 1",
    "SkyStore Premier 2": "SkyStore Premier 2",
    "SkyStore Premier 3": "SkyStore Premier 3",
    "SkyStore Premier 4": "SkyStore Premier 4",
    "SkyStore Premier 5": "SkyStore Premier 5",
    "OSN Movies Family": "OSN Movies Family",
    "OSN MOVIES Hollywood HD": "OSN MOVIES Hollywood HD",
    "OSN MOVIES ACTION HD": "OSN MOVIES ACTION HD",
    "OSN MOVIES PREMIERE": "OSN MOVIES PREMIERE",
    "OSN COMEDY": "OSN COMEDY",
    "HBO Max": "HBO Max",
    "HBO TOP10": "HBO TOP10",
    "STARZPLAY Action": "STARZPLAY Action",
    "Canal+ Box Office2": "Canal+ Box Office2",
    "Canal+ Box Office3": "Canal+ Box Office3",
    "Canal+ Box Office4": "Canal+ Box Office4",
    "Canal+ Box Office5": "Canal+ Box Office5",
    "Canal+ Box Office6": "Canal+ Box Office6",
    "Canal+ Box Office7": "Canal+ Box Office7",
    "Canal+ Box Office8": "Canal+ Box Office8",
    "Canal+ Box Office9": "Canal+ Box Office9",
    "Canal+ Box Office10": "Canal+ Box Office10",
    "Canal+ Box Office11": "Canal+ Box Office11",
    "Canal+ Box Office12": "Canal+ Box Office12",
    "Canal+ Box Office13": "Canal+ Box Office13",
    "Canal+ Box Office14": "Canal+ Box Office14",
    "Canal+ Box Office15": "Canal+ Box Office15",
    "Canal+ Box Office16": "Canal+ Box Office16",
    "Canal+ Box Office17": "Canal+ Box Office17",
    "Canal+ Box Office18": "Canal+ Box Office18",
    "Canal+ Box Office19": "Canal+ Box Office19",
    "beIN MOVIES HD 1 PREMIERE": "beIN MOVIES HD 1 PREMIERE",
    "beIN MOVIES HD 2 ACTION": "beIN MOVIES HD 2 ACTION",
    "Dubai One": "Dubai One",
    "OSN YAHALA CINEMA HD": "OSN YAHALA CINEMA HD",
    "OSN YAHALA Aflam": "OSN YAHALA Aflam",
    "Abu Dhabi Oula HD": "Abu Dhabi Oula HD",
    "Al Emarat TV": "Al Emarat TV",
    "Dubai TV": "Dubai TV",
    "Disney+ 2": "Disney+ 2",
    "Sama Dubai": "Sama Dubai",
    "Sharjah TV": "Sharjah TV",
    "Sharjah 2": "Sharjah 2",
    "Noor Dubai": "Noor Dubai",
    "MBC 1": "MBC 1",
    "MBC 1 KSA": "MBC 1 KSA",
    "MBC 4": "MBC 4",
    "MBC 5": "MBC 5",
    "MBC Drama": "MBC Drama",
    "MBC Masr 1": "MBC Masr 1",
    "MBC Masr 2": "MBC Masr 2",
    "MBC Plus Drama": "MBC Plus Drama",
    "National Geographic Abu Dhabi": "National Geographic Abu Dhabi",
    "Al Jazeera Documentary": "Al Jazeera Documentary",
    "Alaraby TV": "Alaraby TV",
    "Alaraby TV 2": "Alaraby TV 2",
    "FATAFEAT HD": "FATAFEAT HD",
    "Samira TV": "Samira TV",
    "Echorouk TV": "Echorouk TV",
    "Echorouk News": "Echorouk News",
    "El Bilad": "El Bilad",
    "Ennahar TV": "Ennahar TV",
    "Algerie TV1": "Algerie TV1",
    "Algerie TV2": "Algerie TV2",
    "Algerie TV3": "Algerie TV3",
    "Algerie TV6": "Algerie TV6",
    "Nature Time": "Nature Time",
    "Asharq Discovery": "Asharq Discovery",
    "Asharq Documentary": "Asharq Documentary",
    "Al Jazeera": "Al Jazeera",
    "Skynews Arabia": "Skynews Arabia",
    "Al Arabiya": "Al Arabiya",
    "BBC Arabic": "BBC Arabic",
    "DW Arabic": "DW Arabic",
    "RT Arabic": "RT Arabic",
    "TRT Arabi": "TRT Arabi",
    "TF1": "TF1",
    "FRANCE 2": "FRANCE 2",
    "France 3": "France 3",
    "FRANCE 4": "FRANCE 4",
    "FRANCE 5": "FRANCE 5",
    "TV5 Style HD": "TV5 Style HD",
    "TV5 Style": "TV5 Style",
    "M6": "M6",
    "ARTE": "ARTE",
    "Canal+ Docs": "Canal+ Docs",
    "Discovery Channel": "Discovery Channel",
    "Science & Vie": "Science & Vie",
    "Canal+ France": "Canal+ France",
    "Canal+ France": "Canal+ France",
    "Franceinfo": "Franceinfo",
    "Euronews": "Euronews",
    "CNews": "CNews",
    "France 24": "France 24",
    "TF1 Backup": "TF1",
    "FRANCE 2 Backup": "FRANCE 2",
    "France 3 Backup": "France 3",
    "FRANCE 4 Backup": "FRANCE 4",
    "FRANCE 5 Backup": "FRANCE 5",
    "M6 Backup": "M6",
    "Majid TV": "Majid TV",
    "Jeem TV": "Jeem TV",
    "Sky Cinema Animation": "Sky Cinema Animation",
    "Disney+ 2": "Disney+ 2",
    "beIN MOVIES HD 4 FAMILY": "beIN MOVIES HD 4 FAMILY",
    "OSN Kids": "OSN Kids",
    "MBC 3": "MBC 3",
    "Cartoon Network Arabia": "Cartoon Network Arabia",
    "FRANCE 4": "FRANCE 4",
    "Spacetoon": "Spacetoon",
    "BEIN SPORTS 1 HD": "BEIN SPORTS 1 HD",
    "BEIN SPORTS 2 HD": "BEIN SPORTS 2 HD",
    "BEIN SPORTS 3 HD": "BEIN SPORTS 3 HD",
    "BEIN SPORTS 4 HD": "BEIN SPORTS 4 HD",
    "BEIN SPORTS 5 HD": "BEIN SPORTS 5 HD",
    "BEIN SPORTS 6 HD": "BEIN SPORTS 6 HD",
    "BEIN SPORTS 7 HD": "BEIN SPORTS 7 HD",
    "BEIN SPORTS 8 HD": "BEIN SPORTS 8 HD",
    "BEIN SPORTS 1 FHD": "BEIN SPORTS 1 FHD",
    "BEIN SPORTS 2 FHD": "BEIN SPORTS 2 FHD",
    "BEIN SPORTS 3 FHD": "BEIN SPORTS 3 FHD",
    "BEIN SPORTS 4 FHD": "BEIN SPORTS 4 FHD",
    "BEIN SPORTS 5 FHD": "BEIN SPORTS 5 FHD",
    "BEIN SPORTS 6 FHD": "BEIN SPORTS 6 FHD",
    "BEIN SPORTS 7 FHD": "BEIN SPORTS 7 FHD",
    "BEIN SPORTS 8 FHD": "BEIN SPORTS 8 FHD",
    "BEIN SPORTS 1 4K": "BEIN SPORTS 1 4K",
    "BEIN SPORTS 2 4K": "BEIN SPORTS 2 4K",
    "BEIN SPORTS  2 4K": "BEIN SPORTS  2 4K",
    "BEIN SPORTS 3 4K": "BEIN SPORTS 3 4K",
    "BEIN SPORTS 4 4K": "BEIN SPORTS 4 4K",
    "BEIN SPORTS 5 4K": "BEIN SPORTS 5 4K",
    "BEIN SPORTS 6 4K": "BEIN SPORTS 6 4K",
    "BEIN SPORTS 7 4K": "BEIN SPORTS 7 4K",
    "BEIN SPORTS 8 4K": "BEIN SPORTS 8 4K",
    "BEIN SPORTS 1 HEVC": "BEIN SPORTS 1 HEVC",
    "BEIN SPORTS 2 HEVC": "BEIN SPORTS 2 HEVC",
    "BEIN SPORTS 3 HEVC": "BEIN SPORTS 3 HEVC",
    "BEIN SPORTS 4 HEVC": "BEIN SPORTS 4 HEVC",
    "BEIN SPORTS 5 HEVC": "BEIN SPORTS 5 HEVC",
    "BEIN SPORTS 6 HEVC": "BEIN SPORTS 6 HEVC",
    "BEIN SPORTS 7 HEVC": "BEIN SPORTS 7 HEVC",
    "BEIN SPORTS 8 HEVC": "BEIN SPORTS 8 HEVC",
    "BEIN SPORTS XTRA 1 HD": "BEIN SPORTS XTRA 1 HD",
    "BEIN SPORTS XTRA 2 HD": "BEIN SPORTS XTRA 2 HD",
    "BEIN SPORTS XTRA 3 HD": "BEIN SPORTS XTRA 3 HD",
    "BEIN SPORTS ENGLISH 1 HD": "BEIN SPORTS ENGLISH 1 HD",
    "BEIN SPORTS ENGLISH 2 HD": "BEIN SPORTS ENGLISH 2 HD",
    "BEIN SPORTS ENGLISH 3 HD": "BEIN SPORTS ENGLISH 3 HD",
    "BEIN SPORTS FRENCH 1 HD": "BEIN SPORTS FRENCH 1 HD",
    "BEIN SPORTS FRENCH 2 HD": "BEIN SPORTS FRENCH 2 HD",
    "BEIN SPORTS FRENCH 3 HD": "BEIN SPORTS FRENCH 3 HD",
    "BEIN SPORTS NEWS": "BEIN SPORTS NEWS",
    "BEIN SPORTS 2 MAX FHD": "BEIN SPORTS 2 MAX FHD",
    "BEIN SPORTS 4 MAX SD": "BEIN SPORTS 4 MAX SD",
    "BEIN SPORTS GLOBAL HD": "BEIN SPORTS GLOBAL HD",
    "BEIN SPORTS 1 SD": "BEIN SPORTS 1 SD",
    "BEIN SPORTS 2 SD": "BEIN SPORTS 2 SD",
    "BEIN SPORTS 3 SD": "BEIN SPORTS 3 SD",
    "BEIN SPORTS 4 SD": "BEIN SPORTS 4 SD",
    "BEIN SPORTS 5 SD": "BEIN SPORTS 5 SD",
    "BEIN SPORTS 6 SD": "BEIN SPORTS 6 SD",
    "BEIN SPORTS 7 SD": "BEIN SPORTS 7 SD",
    "BEIN SPORTS 8 SD": "BEIN SPORTS 8 SD",
}

STATIC_CATEGORIES = {
    "MBC 2": "🇸🇦沙特阿拉伯",
    "MBC Max": "🇸🇦沙特阿拉伯",
    "MBC Action": "🇸🇦沙特阿拉伯",
    "MBC Movies": "🇸🇦沙特阿拉伯",
    "MBC Movies Action": "🇸🇦沙特阿拉伯",
    "MBC Movies Thriller": "🇸🇦沙特阿拉伯",
    "Canal+ Cinema": "🇫🇷法兰西公共",
    "Canal+ Box Office": "🇫🇷法兰西公共",
    "Canal+ Grand Ecran": "🇫🇷法兰西公共",
    "Canal+ France": "🇫🇷法兰西公共",
    "SkyCinema Premiere": "🇬🇧英格兰+",
    "SkyCinema Action": "🇬🇧英格兰+",
    "SkyStore Premier 1": "🇬🇧英格兰+",
    "SkyStore Premier 2": "🇬🇧英格兰+",
    "SkyStore Premier 3": "🇬🇧英格兰+",
    "SkyStore Premier 4": "🇬🇧英格兰+",
    "SkyStore Premier 5": "🇬🇧英格兰+",
    "OSN Movies Family": "🇸🇦沙特阿拉伯",
    "OSN MOVIES Hollywood HD": "🇸🇦沙特阿拉伯",
    "OSN MOVIES ACTION HD": "🇸🇦沙特阿拉伯",
    "OSN MOVIES PREMIERE": "🇸🇦沙特阿拉伯",
    "OSN COMEDY": "🇸🇦沙特阿拉伯",
    "HBO Max": "🇺🇸美国+",
    "HBO TOP10": "🇺🇸美国+",
    "Disney+ 2": "🇺🇸美国+",
    "STARZPLAY Action": "🇺🇸美国+",
    "Canal+ Box Office2": "🇫🇷法兰西公共",
    "Canal+ Box Office3": "🇫🇷法兰西公共",
    "Canal+ Box Office4": "🇫🇷法兰西公共",
    "Canal+ Box Office5": "🇫🇷法兰西公共",
    "Canal+ Box Office6": "🇫🇷法兰西公共",
    "Canal+ Box Office7": "🇫🇷法兰西公共",
    "Canal+ Box Office8": "🇫🇷法兰西公共",
    "Canal+ Box Office9": "🇫🇷法兰西公共",
    "Canal+ Box Office10": "🇫🇷法兰西公共",
    "Canal+ Box Office11": "🇫🇷法兰西公共",
    "Canal+ Box Office12": "🇫🇷法兰西公共",
    "Canal+ Box Office13": "🇫🇷法兰西公共",
    "Canal+ Box Office14": "🇫🇷法兰西公共",
    "Canal+ Box Office15": "🇫🇷法兰西公共",
    "Canal+ Box Office16": "🇫🇷法兰西公共",
    "Canal+ Box Office17": "🇫🇷法兰西公共",
    "Canal+ Box Office18": "🇫🇷法兰西公共",
    "Canal+ Box Office19": "🇫🇷法兰西公共",
    "beIN MOVIES HD 1 PREMIERE": "🇶🇦卡塔尔",
    "beIN MOVIES HD 2 ACTION": "🇶🇦卡塔尔",
    "Dubai One": "🇦🇪阿联酋",
    "OSN YAHALA CINEMA HD": "🇸🇦沙特阿拉伯",
    "OSN YAHALA Aflam": "🇸🇦沙特阿拉伯",
    "Abu Dhabi Oula HD": "🇦🇪阿联酋",
    "Al Emarat TV": "🇦🇪阿联酋",
    "Dubai TV": "🇦🇪阿联酋",
    "Sama Dubai": "🇦🇪阿联酋",
    "Sharjah TV": "🇦🇪阿联酋",
    "Sharjah 2": "🇦🇪阿联酋",
    "Noor Dubai": "🇦🇪阿联酋",
    "MBC 1": "🇸🇦沙特阿拉伯",
    "MBC 1 KSA": "🇸🇦沙特阿拉伯",
    "MBC 4": "🇸🇦沙特阿拉伯",
    "MBC 5": "🇸🇦沙特阿拉伯",
    "MBC Drama": "🇸🇦沙特阿拉伯",
    "MBC Masr 1": "🇪🇬埃及",
    "MBC Masr 2": "🇪🇬埃及",
    "MBC Plus Drama": "🇸🇦沙特阿拉伯",
    "National Geographic Abu Dhabi": "🇦🇪阿联酋",
    "Al Jazeera Documentary": "🇶🇦卡塔尔",
    "Alaraby TV": "🇸🇦沙特阿拉伯",
    "Alaraby TV 2": "🇸🇦沙特阿拉伯",
    "FATAFEAT HD": "🇸🇦沙特阿拉伯",
    "Samira TV": "🇩🇿阿尔及利亚",
    "Echorouk TV": "🇩🇿阿尔及利亚",
    "Echorouk News": "🇩🇿阿尔及利亚",
    "El Bilad": "🇩🇿阿尔及利亚",
    "Ennahar TV": "🇩🇿阿尔及利亚",
    "Algerie TV1": "🇩🇿阿尔及利亚",
    "Algerie TV2": "🇩🇿阿尔及利亚",
    "Algerie TV3": "🇩🇿阿尔及利亚",
    "Algerie TV6": "🇩🇿阿尔及利亚",
    "Nature Time": "🇶🇦卡塔尔",
    "Asharq Discovery": "🇶🇦卡塔尔",
    "Asharq Documentary": "🇶🇦卡塔尔",
    "Al Jazeera": "🇶🇦卡塔尔",
    "Skynews Arabia": "🇸🇦沙特阿拉伯",
    "Al Arabiya": "🇸🇦沙特阿拉伯",
    "BBC Arabic": "🇬🇧英格兰+",
    "DW Arabic": "🇩🇪德意志",
    "RT Arabic": "🇷🇺俄罗斯新闻",
    "TRT Arabi": "🇹🇷土耳其",
    "TF1": "🇫🇷法兰西公共",
    "FRANCE 2": "🇫🇷法兰西公共",
    "France 3": "🇫🇷法兰西公共",
    "FRANCE 4": "🇫🇷法兰西公共",
    "FRANCE 5": "🇫🇷法兰西公共",
    "TV5 Style HD": "🇫🇷法兰西公共",
    "TV5 Style": "🇫🇷法兰西公共",
    "M6": "🇫🇷法兰西公共",
    "ARTE": "🇫🇷法兰西公共",
    "Canal+ Docs": "🇫🇷法兰西公共",
    "Discovery Channel": "🇺🇸美国+",
    "Science & Vie": "🇫🇷法兰西公共",
    "Canal+ France": "🇫🇷法兰西公共",
    "Franceinfo": "🇫🇷法兰西公共",
    "Euronews": "🇪🇺法兰西新闻",
    "CNews": "🇫🇷法兰西公共",
    "France 24": "🇫🇷法兰西公共",
    "TF1 Backup": "🇫🇷法兰西公共",
    "FRANCE 2 Backup": "🇫🇷法兰西公共",
    "France 3 Backup": "🇫🇷法兰西公共",
    "FRANCE 4 Backup": "🇫🇷法兰西公共",
    "FRANCE 5 Backup": "🇫🇷法兰西公共",
    "M6 Backup": "🇫🇷法兰西公共",
    "Majid TV": "🇸🇦沙特阿拉伯",
    "Jeem TV": "🇸🇦沙特阿拉伯",
    "Sky Cinema Animation": "🇬🇧英格兰+",
    "Disney+ 2": "🇺🇸美国++",
    "beIN MOVIES HD 4 FAMILY": "🇶🇦卡塔尔",
    "OSN Kids": "🇦🇪阿联酋",
    "MBC 3": "🇸🇦沙特阿拉伯",
    "Cartoon Network Arabia": "🇸🇦沙特阿拉伯",
    "Spacetoon": "🇸🇦沙特阿拉伯",
    "BEIN SPORTS 1 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 3 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 5 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 6 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 7 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 8 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 1 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 3 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 5 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 6 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 7 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 8 FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 1 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS  2 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 3 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 5 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 6 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 7 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 8 4K": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 1 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 3 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 5 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 6 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 7 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 8 HEVC": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS XTRA 1 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS XTRA 2 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS XTRA 3 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS ENGLISH 1 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS ENGLISH 2 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS ENGLISH 3 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS FRENCH 1 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS FRENCH 2 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS FRENCH 3 HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS NEWS": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 MAX FHD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 MAX SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS GLOBAL HD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 1 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 2 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 3 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 4 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 5 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 6 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 7 SD": "🇶🇦卡塔尔体育+",
    "BEIN SPORTS 8 SD": "🇶🇦卡塔尔体育+",
}

# 下载 M3U 文件并保存为指定路径
def download_file(url, output_file):
    try:
        print(f"正在下载文件: {url} ...")
        urllib.request.urlretrieve(url, output_file)
        print(f"文件已下载至: {output_file}")
    except Exception as e:
        print(f"下载文件时发生错误: {e}")
        traceback.print_exc()

# 更新 M3U 文件的函数
def update_m3u_file(input_file, output_file, categories, tv_names):
    try:
        # 打开输入文件并读取内容
        print(f"正在打开文件: {input_file}...")
        with open(input_file, 'r', encoding='utf-8-sig') as file:
            lines = file.readlines()

        print("读取文件内容:")
        for line in lines:
            print(line.strip())  # 打印每一行内容，帮助调试

        updated_lines = []
        for line in lines:
            if line.startswith('#EXTINF'):
                # 提取频道名称
                original_channel_name = line.split(',')[1].strip()
                print(f"正在处理频道: {original_channel_name}")  # 打印正在处理的频道名称

                # 标准化频道名称
                channel_name = tv_names.get(original_channel_name, original_channel_name)
                print(f"标准化频道名称: {channel_name}")

                # 如果频道名称在字典中，更新 group-title
                if channel_name in categories:
                    category = categories[channel_name]
                    updated_line = f'#EXTINF:-1 tvg-id="{channel_name}" tvg-logo="https://mchoumi.github.io/LOGOs/{channel_name.replace(" ", "")}.png" group-title="{category}", {channel_name}\n'
                    updated_lines.append(updated_line)
                else:
                    updated_lines.append(line)
            else:
                updated_lines.append(line)

        print("更新后的内容:")
        for updated_line in updated_lines:
            print(updated_line.strip())  # 打印更新后的每一行

        # 写回更新后的内容到新的文件
        with open(output_file, 'w', encoding='utf-8') as file:
            file.writelines(updated_lines)
        print(f"文件已成功更新并保存为: {output_file}")

    except Exception as e:
        print(f"执行时发生错误: {e}")
        # 打印详细的错误堆栈信息
        traceback.print_exc()

# 主程序
def main():
    url = 'https://raw.githubusercontent.com/mchoumi/mchoumi.github.io/refs/heads/main/IPTVara.m3u'
    input_file = 'IPTVara.m3u'
    output_file = 'eup.m3u'  # 更新输出文件名为 'eup.m3u'

    # 1. 下载文件
    download_file(url, input_file)

    # 2. 更新 M3U 文件
    update_m3u_file(input_file, output_file, STATIC_CATEGORIES, STATIC_TV_NAMES)

if __name__ == "__main__":
    main()
