name: arabsee

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每三天执行一次
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  update_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Delete old M3U files from project page
      run: |
        rm -f ara.m3u ARAB.m3u

    - name: Run arabsee script to download and update M3U
      run: |
        python arabsee.py

    - name: Check if M3U files exist
      run: |
        if [ -f "ara.m3u" ]; then
          echo "ara.m3u exists"
        else
          echo "ara.m3u does not exist"
        fi
        if [ -f "ARAB.m3u" ]; then
          echo "ARAB.m3u exists"
        else
          echo "ARAB.m3u does not exist"
        fi

    - name: Commit and push updated M3U files
      run: |
        if [ -f "ara.m3u" ]; then
          git add ara.m3u
        fi
        if [ -f "ARAB.m3u" ]; then
          git add ARAB.m3u
        fi
        git config --global user.email "youremail@example.com"
        git config --global user.name "Your Name"
        git commit -m "Update M3U files"
        git push origin main
