name: arabsee

on:
  schedule:
    - cron: "0 0 */3 * *"  # 每三天执行一次
  push:
    branches:
      - main  # 每次推送到 main 分支时也会执行

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout 仓库

    - name: Remove old M3U files
      run: |
        rm -f ara.m3u  # 删除旧的 ara.m3u 文件
        rm -f ARAB.m3u  # 删除旧的 ARAB.m3u 文件

    - name: Download M3U file and run script
      run: |
        curl -o ara.m3u https://raw.githubusercontent.com/hemzaberkane/ARAB-IPTV/refs/heads/main/ARABIPTV.m3u  # 下载 M3U 文件
        python arabsee.py  # 执行 Python 脚本来生成新的 M3U 文件

    - name: Commit and push M3U files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ara.m3u ARAB.m3u  # 添加生成的文件
        git commit -m "Update M3U files"
        git push  # 推送到 GitHub 仓库
