name: Generate M3U Playlist

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天的 UTC 时间 00:00 执行

jobs:
  generate_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run M3U script
      run: |
        python Eursee.py
