name: Run eursee.py every hour

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次，0 分钟触发
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装所需依赖

      - name: Run eursee.py
        run: python eursee.py  # 执行脚本
