name: Run Python Scripts and Push Results

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 0 分执行
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove old M3U files (if any)
        run: |
          # 删除根目录下旧的 all.m3u 和 Eur.m3u 文件（如果存在）
          if git ls-files --error-unmatch all.m3u > /dev/null 2>&1; then
            git rm -f all.m3u
          fi
          if git ls-files --error-unmatch Eur.m3u > /dev/null 2>&1; then
            git rm -f Eur.m3u
          fi
          git commit -m "Remove old M3U files from root directory" || echo "No old files to remove"

      - name: Run eursee.py to generate all.m3u and Eur.m3u
        run: |
          python eursee.py

      - name: Check if Eur.m3u exists
        run: |
          if [ ! -f "Eur.m3u" ]; then
            echo "Error: Eur.m3u was not created."
            exit 1
          fi
          echo "Eur.m3u file exists."

      - name: Run eur.py to generate eur.m3u
        run: |
          python eur.py

      - name: Check if eur.m3u exists
        run: |
          if [ ! -f "eur.m3u" ]; then
            echo "Error: eur.m3u was not created."
            exit 1
          fi
          echo "eur.m3u file exists."

      - name: Commit and push new M3U files
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          
          # 添加并提交更新的 M3U 文件
          git add all.m3u Eur.m3u eur.m3u
          git commit -m "Update M3U playlists" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
