name: Run Python Script and Push Results

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python eursee.py

      - name: Commit and push new playlist
        run: |
          # 将 all.m3u 和 new_playlist.m3u 文件推送到仓库
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"

          # 将 all.m3u 文件添加到 Git 仓库
          git add docs/all.m3u
          git commit -m "Update all.m3u file"
          git push

          # 将 new_playlist.m3u 文件添加到 Git 仓库
          git add docs/new_playlist.m3u
          git commit -m "Update new_playlist.m3u file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
