name: Run Python Script and Push Results

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python eursee.py

      - name: Remove old files from docs (if any)
        run: |
          # 检查 docs 文件夹下是否存在 all.m3u 和 new_playlist.m3u 文件
          if git ls-files --error-unmatch docs/all.m3u > /dev/null 2>&1; then
            git rm -f docs/all.m3u
          fi
          if git ls-files --error-unmatch docs/new_playlist.m3u > /dev/null 2>&1; then
            git rm -f docs/new_playlist.m3u
          fi
          git commit -m "Remove old playlist files" || echo "No old files to remove"

      - name: Commit and push new playlist
        run: |
          # 配置 Git 用户信息
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          
          # 将 all.m3u 和 new_playlist.m3u 文件添加到 Git 仓库
          git add docs/all.m3u
          git add docs/new_playlist.m3u
          git commit -m "Update all.m3u and new_playlist.m3u files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
