name: Generate and Push M3U Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 0 分执行
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (如果有依赖项)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Remove old M3U files (if any)
      - name: Remove old M3U files
        run: |
          # 删除根目录下的旧 M3U 文件（如果存在）
          if git ls-files --error-unmatch all.m3u > /dev/null 2>&1; then
            git rm -f all.m3u
          fi
          if git ls-files --error-unmatch eur.m3u > /dev/null 2>&1; then
            git rm -f eur.m3u
          fi
          git commit -m "Remove old M3U files" || echo "No old files to remove"

      # Step 5: Run eursee.py to generate all.m3u and Eur.m3u
      - name: Run eursee.py
        run: |
          python eursee.py
          
      # Step 6: Run eur.py to process Eur.m3u
      - name: Run eur.py to process Eur.m3u
        run: |
          python eur.py

      # Step 7: Commit and push the new M3U files
      - name: Commit and push new M3U files
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          
          # Add the new M3U files and commit
          git add all.m3u eur.m3u
          git commit -m "Update all.m3u and eur.m3u" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
