name: Run Python Script and Push Results

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove old M3U files (if any)
        run: |
          # 删除根目录下旧的 all.m3u 和 Eur.m3u 文件（如果存在）
          if git ls-files --error-unmatch all.m3u > /dev/null 2>&1; then
            git rm -f all.m3u
          fi
          if git ls-files --error-unmatch Eur.m3u > /dev/null 2>&1; then
            git rm -f Eur.m3u
          fi
          git commit -m "Remove old M3U files from root directory" || echo "No old files to remove"

      - name: Run script
        run: |
          python eursee.py

      - name: Check if new files were created
        run: |
          if [ ! -f "all.m3u" ]; then
            echo "Error: all.m3u was not created."
            exit 1
          fi
          if [ ! -f "Eur.m3u" ]; then
            echo "Error: Eur.m3u was not created."
            exit 1
          fi

      - name: Commit and push new M3U files
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          
          # 强制提交，确保没有更改也能推送
          git add all.m3u Eur.m3u
          git commit -m "Update M3U playlists" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
