name: Run Python Script and Push Results

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python eursee.py

      - name: Commit and push new playlist
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add new_playlist.m3u
          git commit -m "Update new playlist"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
